### PR TITLE
Release package version 0.4.4.

### PR DESCRIPTION
**Pull request by mkcor**
## About
Follows #443.

## Description of changes
Note that the `postbuild` is failing. The rest looks fine.

## Before merging
- [ ] I have gone through the [code review checklist](https://github.com/plotly/dash-component-boilerplate/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/review_checklist.md)
- [ ] I have completed all of the [steps to take before merging](https://github.com/plotly/dash-bio/blob/master/.github/before_merging.md)
- [ ] I know how to [deploy to DDS](https://github.com/plotly/dash-bio/blob/master/.github/deploying_to_dds.md)

### CODE REVIEW

**Comment by mkcor** [comment]
@shammamah Can you publish it to PyPI (or give me permission to do so)?

**Comment by shammamah** [comment]
@mkcor Which part of the `postbuild` is failing?

**Comment by mkcor** [comment]
```bash
$ npm run postbuild

> dash-bio@0.4.4 postbuild /home/marianne/Work/Plotly/dash-bio
> es-check es5 dash_bio/*.js

ES-Check: there were 1 ES version matching errors.

          ES-Check Error:
          ----
          · erroring file: dash_bio/async~moleculeviewer3.js
          · error: SyntaxError: The keyword 'const' is reserved (1:132731)
          · see the printed err.stack below for context
          ----

          SyntaxError: The keyword 'const' is reserved (1:132731)
[...]
```

**Comment by shammamah** [comment]
Hm, that's interesting that it's only popping up now. Looks like the `postbuild` isn't automatically called when the package is built in `development` mode. Good catch! 

Let's wait to release `0.4.4` until that `postbuild` error is resolved. I can take over this PR in the meantime.

**Comment by mkcor** [comment]
> Looks like the `postbuild` isn't automatically called when the package is built in `development` mode.

Exactly.

> Let's wait to release `0.4.4` until that `postbuild` error is resolved. I can take over this PR in the meantime.

Perfect, leaving this PR in your hands. Thanks!

**Pull request merged**
