### PR TITLE
change to plotly dash logo

### PR DESCRIPTION
**Pull request by celinehuang**
## Changes
- update logos of all `dash-bio` 

https://dash-gallery.plotly.host/dash-circos/
https://dash-gallery.plotly.host/dash-clustergram/
https://dash-gallery.plotly.host/dash-ideogram/
https://dash-gallery.plotly.host/dash-manhattan-plot/
https://dash-gallery.plotly.host/dash-molecule3d/
https://dash-gallery.plotly.host/dash-needle-plot/
https://dash-gallery.plotly.host/dash-onco-print/
https://dash-gallery.plotly.host/dash-sequence-viewer/
https://dash-gallery.plotly.host/dash-speck/
https://dash-gallery.plotly.host/dash-volcano-plot/

### CODE REVIEW

**Comment by shammamah** [comment]
Not sure I'm loving this layout: 
Screen Shot 2019-07-26 at 4 11 01 PM

**Comment by shammamah** [comment]
@celinehuang We've decided to actually just remove the word "Dash" from the titles of the apps, so just change this line: 

https://github.com/plotly/dash-bio/blob/241a9728ed874142204bb43f2bcb75d9a1475ce0/tests/dashbio_demos/utils/app_standalone.py#L25

by removing the "Dash". Could you also change the logo to be this: (it's white and transparent, so if you can't see it that's why :P)

all white dash logo@2x

**Comment by celinehuang** [comment]
screencapture-localhost-8050-2019-07-26-19_31_25
Is this what you mean? @shammamah

**Comment by shammamah** [comment]
@celinehuang Yes, that's perfect :)

**Pull request merged**
