### PR TITLE
[WIP] Genome viewer

### PR DESCRIPTION
**Pull request by emmanuelle**
Follow-up of #115, which I closed by accident.

# Dash Bio pull request
- [x] This is a new component 

## Name and description of your component
GenomeViewer, from https://github.com/plotly/react-genome-viewer by @jackluo. A tool for visualization and comparison of genome sequences, built on top of pileup.js

## Main libraries used in component
* pileup from hammerlab https://github.com/hammerlab/pileup.js/

I added the GenomeViewer component from the ``react-genome-viewer``. This is still work in progress, for some reason I cannot generate all tracks as show on the image below. The reason seems to be that local files cannot be read from file paths, ``pileup`` needs a file server to serve data files as URLs. Ideas about how to do this properly are very welcome, otherwise I'll explore along the lines of plotly/dash#71

image

to be compared to the ``react-genome-viewer`` repo 

image

### CODE REVIEW

**Comment by emmanuelle** [comment]
Hurray, I solved the file serving problem! Now the app displays correctly :-). @shammamah @jackluo

**Comment by emmanuelle** [comment]
I wonder why this branch was not deployed....

**Comment by Bachibouzouk** [comment]
> I wonder why this branch was not deployed....

You need to setup its deployement on heroku :), I did it for you (the deployment), if you need credentials for heroku you should ask someone with admin rights :)

**Comment by emmanuelle** [comment]
Thank you @Bachibouzouk ! I'm used to deploying my apps to heroku using my own account, but maybe I need other credentials here...

**Comment by Bachibouzouk** [comment]
@emmanuelle : I wonder why the CircleCI tests are not running on this PR?

**Comment by jackparmer** [comment]
This app is going to be so cool! One thing I noticed though, I couldn't get datasets other than `chr17` to load on https://dash-bio-test-pr-137.herokuapp.com/dash-bio/genome-viewer

image

Didn't look into it too much, but perhaps have to host these datasets on the same server:

image

**Comment by emmanuelle** [comment]
@jackparmer the same behavior is observed for the original app of the hammer lab (see http://www.hammerlab.org/pileup/); it is due to the fact that the set of files used for comparisons correspond to one chromosome only. I'll see if I can tinker with the app so that it behaves better when another chomosome is asked for (or so that it's not possible to change chromosome).

**Comment by emmanuelle** [comment]
The app lives on https://dash-bio-genome-viewer.herokuapp.com

**Comment by emmanuelle** [comment]
@shammamah @jackparmer what's next for you so that the app can get merged? I played around with a dcc Checklist to see if I can select which tracks are visible, this might be a cool feature (but no luck for now, tracks do update but are blank, I need to investigate more). Anything else which you would like to have?

**Comment by shammamah** [comment]
@emmanuelle Great job with the component and the app -- it looks really good! 

I'd say for now, it would be nice to have some of the features of the other apps. For example, the Circos app (https://dash-bio-genome-viewer.herokuapp.com/dash-bio/circos) has different datasets available to switch between, as well as a button that allows you to download a dataset that you can then upload through a `dcc.Upload` component (in the "Custom graph" tab). 

Don't worry about rushing this at all! I've actually put a freeze on the components in the repo right now, so we won't be merging anything new until a while after the release (~18 Feb). We're also working on adding tests for all components, so if you could start working on those that would be great too (let me know if you need some guidance on where to look for more information on that).

**Comment by jackluo** [comment]
@emmanuelle what do you mean by tracks are blank? lmk if i can help you

**Comment by mkcor** [comment]
> I wonder why the CircleCI tests are not running on this PR?

@emmanuelle it might be because this branch lives on a fork...
@shammamah which makes it slightly less straightforward to take over...

**Comment by emmanuelle** [comment]
@mkcor so usually you prefer to push a branch to the plotly/dash-bio repo? I'm used to pushing to my fork for projects like scikit-image for which only a very limited number of persons have push rights... I think you can also push commits to my branch as a maintainer. Otherwise feel free to open a new PR after having fetched my branch. I'd be happy to assist you if you take over, I was still planning to work on it at some point but it had fallen behind because of other projects.

**Comment by mkcor** [comment]
> @mkcor so usually you prefer to push a branch to the plotly/dash-bio repo? I'm used to pushing to my fork for projects like scikit-image for which only a very limited number of persons have push rights...

Sure, pushing to your fork (conventionally, remote `origin`) and pulling from the gatekeeper (conventionally, remote `upstream`) is the standard collaborative workflow for open-source, community-based projects.
Reference: https://www.atlassian.com/git/articles/git-forks-and-upstreams

Remember that Dash Bio was open-sourced only very recently and we don't have an actual *community* of contributors (yet). Ever since I joined the project, I have fuelled the discussion about our collaborative workflow (internally and [indirectly](https://github.com/plotly/dash-bio/pull/156#discussion_r256908786)). So far we have decided to go the Dash [way](https://github.com/plotly/dash/blob/master/CONTRIBUTING.md) (i.e., *you* could work directly on a `plotly/dash-bio` clone).

> I think you can also push commits to my branch as a maintainer.

Hmm, I must say that would surprise (and terrify) me... unless you add me as a collaborator.

> Otherwise feel free to open a new PR after having fetched my branch.

Ok. Thank you, @emmanuelle!

> I'd be happy to assist you if you take over, I was still planning to work on it at some point but it had fallen behind because of other projects.

Story of my life... ;)

**Comment by emmanuelle** [comment]
Thank you @mkcor for the explanations. I made you a collaborator of my fork if you prefer, otherwise a new branch and PR is fine too.

**Comment by mkcor** [comment]
> Thank you @mkcor for the explanations. I made you a collaborator of my fork if you prefer, otherwise a new branch and PR is fine too.

You're welcome, @emmanuelle. Sorry, I should have clarified that I intended to work on a [new branch](https://github.com/plotly/dash-bio/tree/genome-viewer). I only mentioned you adding me as a collaborator to discuss the logic permissions. Will ping you when I submit the (new) PR!

**Comment by shammamah** [comment]
Closing this, as the work is now on #305

**Pull request closed without merging**
