### PR TITLE
Update homepage on PyPI.

### LINKED ISSUE #339: Dash Bio homepage is wrong on PyPI
The link currently leads to a repository titled `dash_bio`, which is nonexistent.

### PR DESCRIPTION
**Pull request by shammamah**
Closes #339 

## Before merging
- [x] I have gone through the [code review checklist](https://github.com/plotly/dash-component-boilerplate/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/review_checklist.md)
- [x] I have completed all of the [steps to take before merging](https://github.com/plotly/dash-bio/blob/master/.github/before_merging.md)
- [x] I know how to [deploy to DDS](https://github.com/plotly/dash-bio/blob/master/.github/deploying_to_dds.md)

### CODE REVIEW

**Comment by shammamah** [comment]
@mkcor OK -- added an entry. I'm wondering if we need to add CHANGELOG entries for every single patch (that seems a little excessive, especially when it's something as minor as this that doesn't affect how the package behaves at all).

**Comment by shammamah** [comment]
For example, the CHANGELOG for Dash (https://github.com/plotly/dash/blob/master/CHANGELOG.md) is only updated for minor versions.

**Comment by mkcor** [comment]
Ok. I think you're misinterpreting what I said. It's the other way around.

I'm only asking for a CHANGELOG entry because you bumped up the version number. Personally, I would have made this tiny change without changing versions... and all this (including WIP docs) would have been smoother and faster.

But if you go from 0.0.9 to 0.0.10 (which I don't think was necessary, I actually think it's a bit odd), somehow you have to justify it... right? I still don't understand why you bumped version number to 0.0.10, but now that you did, I'm trying to make it work somehow.

**Comment by shammamah** [comment]
Actually, you *do* have to bump the version number to edit the metadata. See discussion here: https://github.com/pypa/warehouse/issues/2170#issuecomment-352902581

**Comment by shammamah** [comment]
More info here: https://mail.python.org/pipermail/distutils-sig/2017-December/031826.html

**Comment by mkcor** [comment]
Looking at the CHANGELOG for Dash, it doesn't seem related to anything major/minor/patch/rc. It looks like it's updated whenever there's a version updated, whether minor or patch or anything.

**Comment by shammamah** [comment]
Ah, you're correct! Didn't scroll down far enough :)

**Comment by mkcor** [comment]
That's super interesting, thanks for sharing. But here I'm not really arguing about whether to increment versions or not. Rather, I'm arguing that *if you do so*, then you want to document it.

Do you mind rerunning CI to get those tests to pass?

**Pull request merged**
