### PR TITLE
Support data input as DataFrame in Clustergram.

### LINKED ISSUE #451: Make plots work with pandas dataframes as input
From the documentation, it seems like some dashbio plots (e.g. volcano and manhattan) already work with pandas dataframes, while others (e.g. clustergram) does not. I haven't looked through all the plots, so I don't know how generalizable this suggestion is, but at least for clustergram plots it would be helpful to pass data frames and string references to dataframe columns as inputs.

As an example, instead of writing

```python
db.Clustergram(iris.select_dtypes('number').to_numpy(), row_labels=iris['species'].to_list())
```

it would be more intuitive to write

```python
db.Clustergram(iris, row_labels='species')  # or a reference to a column with color names
```

### PR DESCRIPTION
**Pull request by mkcor**
Closes #451 

## About
- [ ] I am closing an issue
- [ ] This is a new component
- [x] I am adding a feature to an existing component, or improving an existing feature

## Description of changes
With this change, users can now pass dataframes as input. I updated the docstring accordingly.
@shammamah I removed the `None` default for this parameter since it's required...

### CODE REVIEW

**Comment by mkcor** [comment]
@shammamah can you please Percy-review? Thanks!

**Comment by shammamah** [comment]
@mkcor Please add a test to our Clustergram integration tests as well!

**Comment by mkcor** [comment]
Ok. That's also a great pretext for me to fix this part of my testing setup (I've been dragging this WebDriver issue for too long)...

**Comment by mkcor** [comment]
@shammamah Done! The CI fail seems to be an unrelated timeout; do you mind re-running the CI workflow? Thanks.

**Comment by mkcor** [comment]
Still this timeout error with `tests/integration/test_speck.py`... :thinking:

**Comment by mkcor** [comment]
@shammamah pinging you for final review ;)

**Comment by joelostblom** [comment]
This is great! Thank you for adding dataframe support!

**Comment by mkcor** [comment]
@joelostblom I'm glad you're enjoying it!

**Pull request merged**
