### PR TITLE
Rebuild package.

### PR DESCRIPTION
**Pull request by mkcor**
## About
I ran
```bash
npm run build
npm update
npm audit fix
```

## Description of changes
I'm not sure why the `./dash_bio/*.js` files changed as a result... But some catching up must be going on.
I fixed the docs following the [renaming of `build:all`](https://github.com/plotly/dash-bio/commit/a1722b1a4993edef37b4de0a5faefe84c3d6b649), @Marc-Andre-Rivet.
I documented the change we just merged over at #423.

## Before merging
- [ ] I have gone through the [code review checklist](https://github.com/plotly/dash-component-boilerplate/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/review_checklist.md)
- [ ] I have completed all of the [steps to take before merging](https://github.com/plotly/dash-bio/blob/master/.github/before_merging.md)
- [ ] I know how to [deploy to DDS](https://github.com/plotly/dash-bio/blob/master/.github/deploying_to_dds.md)

### CODE REVIEW

**Comment by mkcor** [comment]
@Marc-Andre-Rivet Do you have a clue which "problem with `npm`" it could be?
https://circleci.com/gh/plotly/dash-bio/5238
When running `$ npm run format:test` locally, I'm also getting this error.

**Comment by shammamah** [comment]
@mkcor Could you try deleting your `node_modules` folder, then running the following: 

```
npm i 
npm run build 
npm audit fix
npm run format:test
```

**Comment by shammamah** [comment]
It looks like you've just updated all of the packages blindly with `npm update`, which is probably what's causing the errors.

**Comment by mkcor** [comment]
> It looks like you've just updated all of the packages blindly with `npm update`, which is probably what's causing the errors.

I thought I had a clean setup, but apparently not... watching the progress bar... ;)

**Comment by mkcor** [comment]
For reference:
```bash
$ npm audit fix
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-jsx@5.1.0 requires a peer of acorn@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.4.0 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 17.726s
fixed 0 of 30 vulnerabilities in 912456 scanned packages
  30 vulnerabilities required manual review and could not be updated
```

**Comment by mkcor** [comment]
@shammamah You were right, nuking the `node` env and reinstalling the packages did the job. It's too bad the Renovate Bot isn't doing much for us... :s (#377)

**Comment by mkcor** [comment]
@shammamah Can you Percy-check and approve or would you like me to do the 0.4.4 release as part of the same PR?

**Comment by mkcor** [comment]
:thinking: Since you approved, I'll merge now and submit a separate PR for v0.4.4!

**Pull request merged**
