### PR TITLE
0.0.8 release

### PR DESCRIPTION
**Pull request by shammamah**
## About 
Releasing a new official version of Dash Bio package. 

## Description of changes 
See CHANGELOG. 

## Before merging
- [x] I have gone through the [code review checklist](https://github.com/plotly/dash-component-boilerplate/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/review_checklist.md)
- [x] I have completed all of the [steps to take before merging](https://github.com/plotly/dash-bio/blob/master/.github/before_merging.md)
- [x] I know how to [deploy to DDS](https://github.com/plotly/dash-bio/blob/master/.github/deploying_to_dds.md)

### CODE REVIEW

**Comment by mkcor** [comment]
More, precisely, it is a new *major version zero* (https://semver.org/).

**Comment by mkcor** [comment]
Since I have merged #299 (dependency update), syncing up this branch with `master` will bring a change wrt v0.0.8-rc13. So, then, I'm fine considering that we can increment the version number and, hence, release v0.0.8!

**Comment by mkcor** [comment]
> I think this doesn't make sense, because then version `0.0.8-rc13` and version `0.0.8` are identical... whereas you would expect `0.0.8-rc13 < 0.0.8` (https://semver.org/).

Or maybe it does make sense, since any of the `0.0.8-rc*` versions (release candidates) could have become version `0.0.8` after passing QA and assuming no change was needed... (not sure ;))

**Comment by shammamah** [comment]
@mkcor Yeah, that was my logic! I figure that a release *candidate* shouldn't need to be modified for the release.

**Pull request merged**
