### PR TITLE
Fix Clustergram reordering of row and column indices.

### LINKED ISSUE #432: Clustergram not reordering heat-map rows
**Describe the bug**
Clustergram is not using the order provided by the clustering method and dendrogram to display the heat-map.

**To Reproduce**
```
import numpy as np
import dash_bio
from plotly.offline import iplot, init_notebook_mode

init_notebook_mode()
data = np.array([[1,1,1,1], 
        [3,3,3,3],
        [1,1,1,1],
        [3,3,3,3],
        [1,1,1,1],
        [3,3,3,3]])

iplot(dash_bio.Clustergram(
    data=np.array(data),
    center_values=False
))
```

**Expected behavior**
Heat-map rows reordering based on the clustering result.

**Screenshots**
If applicable, add screenshots to help explain the issue.
image

**Python version: [e.g., 3.7.2]**
3.7.4
**Python environment (all installed packages in your current environment):**
 - 

**Additional context**

### PR DESCRIPTION
**Pull request by mkcor**
Closes #432.

## About
This is a hot fix for the Clustergram component, which used to shuffle rows and/or columns (depending on whether clustering would be along rows, columns, or both) after they were reordered (as expected) from clustering (based on scipy's hierarchy submodule).

All the action is taking place at commit 611a1b358b66694a047e9ddafbf9ea7f9562eea1 (the rest is minor).

I included a unit test (bda8f08bc9c0695716f571a7c4ea4a01b7ca7641) using the example from the bug report (#432).

## Before merging
- [ ] I have gone through the [code review checklist](https://github.com/plotly/dash-component-boilerplate/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/review_checklist.md)
- [ ] I have completed all of the [steps to take before merging](https://github.com/plotly/dash-bio/blob/master/.github/before_merging.md)
- [ ] I know how to [deploy to DDS](https://github.com/plotly/dash-bio/blob/master/.github/deploying_to_dds.md)

### CODE REVIEW

**Comment by mkcor** [comment]
I wonder why `test_dbsv004_coverage_clicked` is failing for Python 3.7... :thinking:

**Comment by mkcor** [comment]
> dancer Once we figure out what is causing that test to fail. Have you done a fresh `npm ci/npm run build/pip install -e .`?

@shammamah must have been that, thanks ;)

**Comment by shammamah** [comment]
@mkcor Please add a CHANGELOG entry and bump the version! I can publish to npm and PyPI.

**Comment by mkcor** [comment]
Aww what's wrong with file `dash_bio/async~moleculeviewer3.js`? :(

**Comment by shammamah** [comment]
You might have to do a full clean (`rm -rf node_modules`) and `npm ci`. :/

**Comment by mkcor** [comment]
When I clean up first, I get the same postbuild error (`"postbuild": "es-check es5 dash_bio/*.js"`) upon running `npm run build` (after `rm -rf node_modules` and `npm ci`)...

**Comment by mkcor** [comment]
I'll try upating `eslint`.

**Comment by mkcor** [comment]
Oh dear, I went through https://flaviocopes.com/update-npm-dependencies/ but still getting this `eslint` postbuild error.

**Comment by shammamah** [comment]
@mkcor Looking into it now!

**Comment by shammamah** [comment]
@mkcor We don't want to update our npm packages here (that's why I suggested `npm ci`). Would you mind reverting those updates?

**Comment by mkcor** [comment]
Duh, I've been trying to run `es-check es5 dash_bio/*.js` while reading that I should upgrade `es5` to `es6`! Pff, I shouldn't work when feeling sickish. Expect a new commit soon!

**Comment by mkcor** [comment]
> @mkcor We don't want to update our npm packages here (that's why I suggested `npm ci`). Would you mind reverting those updates?

Sure. We need to update `eslint` though (see https://github.com/AtomLinter/linter-eslint/issues/592 and apparently that's the spirit of our `.eslintrc` file). Is it okay if I revert all the package updates except for that of `eslint`?

Broader question: Why don't we want to update packages? Originally we set up https://github.com/plotly/dash-bio/pull/377 for this purpose.

**Comment by shammamah** [comment]
>Sure. We need to update eslint though (see AtomLinter/linter-eslint#592 and apparently that's the spirit of our .eslintrc file). Is it okay if I revert all the package updates except for that of eslint?

That sounds fine. 

>Broader question: Why don't we want to update packages? Originally we set up #377 for this purpose.

We don't want to update npm packages (that don't need to be updated) in this PR, since it only modifies one of the Python components.

**Comment by shammamah** [comment]
Also, doing a clean install/build from `master` doesn't give the same error, so since you've only modified the Python parts, there logically shouldn't be any build issues here at all. Nothing has changed on the JS side. 

This commit looks like it was the culprit: https://github.com/plotly/dash-bio/pull/458/commits/d2faa891b13e4fed6de34668c7000cbc689473c4

It seems to have changed the versions of a bunch of packages. Please check out the versions of `package.json` and `package-lock.json` that are on `master`, then `rm -rf node_modules/npm ci/npm install`.

**Comment by mkcor** [comment]
> Also, doing a clean install/build from `master` doesn't give the same error, so since you've only modified the Python parts, there logically shouldn't be any build issues here at all. Nothing has changed on the JS side.

Right, my install/build at d2faa89 must have been messy.

> This commit looks like it was the culprit: [d2faa89](https://github.com/plotly/dash-bio/commit/d2faa891b13e4fed6de34668c7000cbc689473c4)

Thanks for looking into it! I have rebased to remove this commit and all subsequent commits. Then:

* `rm -rf node_modules/`
* edited `package.json` to bump Dash Bio's version to 0.4.6
* `npm ci`
* `npm install`
* committed (b09ff8f)

I updated the date to today's date in the changelog. Then:

* `npm run build`
* committed (e43023f)

Please review the visual change (Percy), thanks!

**Pull request merged**
