### PR TITLE
Speck app improvements

### PR DESCRIPTION
**Pull request by shammamah**
## Description of changes 
Aesthetic changes to the Speck app for the redesign.

(Edit: details of the changes made are below.)
- move all controls/info to a `dcc.Tabs` component, and split them up into categories: "About", "Data", and "View"
- change color of header
- change colours of range slider tracks/handles to match the header color
- change the initial zoom value for the Speck component, so that it doesn't fill up the entire canvas area

## Before merging
- [x] I have gone through the [code review checklist](https://github.com/plotly/dash-component-boilerplate/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/review_checklist.md)
- [x] I have completed all of the [steps to take before merging](https://github.com/plotly/dash-bio/blob/master/.github/before_merging.md)
- [x] I know how to [deploy to DDS](https://github.com/plotly/dash-bio/blob/master/.github/deploying_to_dds.md)

### CODE REVIEW

**Comment by mkcor** [comment]
Since the changes seem to be visual, can you please include a before/after screenshot in the PR description, so I know what to expect / look for?

**Comment by shammamah** [comment]
@mkcor The old version is the one that was last deployed: https://dash-bio.plotly.host/dash-speck/

**Comment by mkcor** [comment]
> @mkcor The old version is the one that was last deployed: https://dash-bio.plotly.host/dash-speck/

Right, so it's most relevant to include a screenshot of the 'after' situation (highlighting the changes brought by the PR).

**Comment by shammamah** [comment]
That's in the test app: https://dash-bio-test-pr-238.herokuapp.com/dash-bio/speck. (Or did you mean using something like Percy? This is a pretty big visual overhaul, so I don't think that would be super useful.)

**Comment by mkcor** [comment]
That's fine. I can get into the habit of visiting URLs... It's just nice to get context when you start reviewing a PR. And I'm definitely not saying it should *always* contain a before/after screenshot but, in this case, I guess I was kind of hoping for a screenshot (or something, anything), since neither the PR title nor description tell you what the changes are about. And sometimes, as might be the case here, it's easier to *show* the changes rather than describe them in words.

**Comment by shammamah** [comment]
That makes sense! I'll be sure to do that in the future. I'll update the PR description to include a summary of the changes.

**Pull request merged**
