### PR TITLE
Update ideogram

### PR DESCRIPTION
**Pull request by mj3cheun**
This PR will also implement the work in #380: 
- [x] Fix prop types/update props to be compliant with [the current API](https://github.com/eweitz/ideogram/blob/master/api.md)
- [x] Remove support for old versions of `ideogram`, which assign to `window.chrBands`
- [x] Remove unnecessary rendered props
- [ ] Histogram annotation fix

## About
- [ ] This is a new component
- [X] I am adding a feature to an existing component, or improving an existing feature
- [ ] I am closing an issue

## Before merging
- [ ] I have gone through the [code review checklist](https://github.com/plotly/dash-component-boilerplate/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/review_checklist.md)
- [ ] I have completed all of the [steps to take before merging](https://github.com/plotly/dash-bio/blob/master/.github/before_merging.md)
- [ ] I know how to [deploy to DDS](https://github.com/plotly/dash-bio/blob/master/.github/deploying_to_dds.md)

### CODE REVIEW

**Comment by mkcor** [comment]
Wow, does it just work? I'd be curious to know what happened on Ideogram's and/or our end to resolve whatever issues had been blocking so far...

**Comment by mj3cheun** [comment]
Haha quite honestly I am not sure why there aren't any failed tests, I was fully expecting there to be. I have tried to update the version before and I believe there were failed tests then. I think it might be worth double checking to make sure that things work as expected. As well, since the existing ideogram tests are not very reliable anyway, I am working on a rewrite of them using ideogram version 1.10.0.

**Comment by mkcor** [comment]
Right, I'm not sure that any of the Ideogram-related tests we currently have would capture the past issues we were experiencing... You may want to look at these issues https://github.com/eweitz/ideogram/issues/created_by/matthewchan15 and maybe #186 (?).

**Comment by mj3cheun** [comment]
Lol i think i figured out what happened, the tests are still using the old version of ideogram. I looked at the deployed version and its missing features and fixes which I know were added in 1.10.0. Same thing is probably happening in the tests.

**Comment by shammamah** [comment]
@mj3cheun Could you increment the version of the package, regenerate the bundle, and republish to NPM?

**Comment by HammadTheOne** [comment]
Closed via #667

**Pull request closed without merging**
