### PR TITLE
Updated dependencies and PropTypes fix

### LINKED ISSUE #313: Molecule3D dependency doesn't work with React version 16.0 and above
In React v15.5, `propTypes` have been moved to an external package (announcement: https://reactjs.org/blog/2017/04/07/react-v15.5.0.html)

From the announcement: 
>Prop types are a feature for runtime validation of props during development. We’ve extracted the built-in prop types to a separate package to reflect the fact that not everybody uses them.
>In 15.5, instead of accessing PropTypes from the main React object, install the prop-types package and import them from there:

The `dash-core-components` library now uses React v16.0 (upgraded from React v15.4), and this results in a breaking change for one of our dependencies (Molecule3D): 

https://github.com/Autodesk/molecule-3d-for-react/blob/ea30999599755f916a1db1d321b198e21348d1a6/src/components/molecule_3d.jsx#L53

https://reactjs.org/warnings/dont-call-proptypes.html#dont-call-proptypes-directly
From the above link: 
>If you don’t fix the warning, this code will crash in production with React 16.

### PR DESCRIPTION
**Pull request by shammamah**
Closes #313 

## About 
- [ ] This is a new component 
- [ ] I am adding a feature to an existing component, or improving an existing feature
- [x] I am closing an issue 

## Description of changes 
* I transferred ownership of all of the forked repos that were under my account to Plotly, and changed the dependency locations to reflect that. 
* In the `molecule-3d-for-react` fork I made, I addressed https://github.com/Autodesk/molecule-3d-for-react/issues/36 and it no longer gives us the error I was getting. 

## Before merging
- [x] I have gone through the [code review checklist](https://github.com/plotly/dash-component-boilerplate/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/review_checklist.md)
- [x] I have completed all of the [steps to take before merging](https://github.com/plotly/dash-bio/blob/master/.github/before_merging.md)
- [x] I know how to [deploy to DDS](https://github.com/plotly/dash-bio/blob/master/.github/deploying_to_dds.md)

### CODE REVIEW

**Comment by mkcor** [comment]
I'm more than happy to approve, but I guess #312 should be merged first, for version numbers to make sense!

**Comment by shammamah** [comment]
@mkcor Latest changes from `master` have been merged in! Should be good to merge now :)

**Comment by mkcor** [comment]
@shammamah do you mind approving #304 first?

**Comment by mkcor** [comment]
Then you'll have to update this branch against `master` again, I know, but #304 is much 'older'...

**Comment by mkcor** [comment]
Thanks, @shammamah! Updated the branch and reviewing now.

**Pull request merged**
