### PR TITLE
modify _Clustergram._scale function

### PR DESCRIPTION
**Pull request by illumination-k**
## About
- a small bug

## Description of changes
When using standarize, Clustergram.scale(self, dim), but using self.scale, self.scale(self._data, standarize) and occured error. So, I simply delete self._data.

## Before merging
- [x] I have gone through the [code review checklist](https://github.com/plotly/dash-component-boilerplate/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/review_checklist.md)
- [x] I have completed all of the [steps to take before merging](https://github.com/plotly/dash-bio/blob/master/.github/before_merging.md)
- [x] I know how to [deploy to DDS](https://github.com/plotly/dash-bio/blob/master/.github/deploying_to_dds.md)

### CODE REVIEW

**Comment by shammamah** [comment]
@illumination-k Could you please post the code that was causing you to get the error (as well as the error itself)?

**Comment by illumination-k** [comment]
This is my code, and only edit [Default Clustergram](https://dash.plot.ly/dash-bio/clustergram), adding standadrize option.
This editing caused `TypeError: _scale() takes 2 positional arguments but 3 were given`.

### code

```
import pandas as pd

import dash
import dash_bio as dashbio
import dash_html_components as html
import dash_core_components as dcc


external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

df = pd.read_csv(
    'https://raw.githubusercontent.com/plotly/dash-bio-docs-files/master/' +
    'clustergram_mtcars.tsv',
    sep='	', skiprows=4
).set_index('model')

columns = list(df.columns.values)
rows = list(df.index)

app.layout = html.Div([
    "Rows to display",
    dcc.Dropdown(
        id='clustergram-input',
        options=[
            {'label': row, 'value': row} for row in list(df.index)
        ],
        value=rows[:10],
        multi=True,
    ),

    html.Div(
        id='my-clustergram'
    )
])


@app.callback(
    dash.dependencies.Output('my-clustergram', 'children'),
    [dash.dependencies.Input('clustergram-input', 'value')]
)
def update_clustergram(rows):
    if len(rows) < 2:
        return "Please select at least two rows to display."

    return dcc.Graph(figure=dashbio.Clustergram(
        data=df.loc[rows].values,
        column_labels=columns,
        row_labels=rows,
        color_threshold={
            'row': 250,
            'col': 700
        },
        hidden_labels='row',
        height=800,
        width=700,
        standardize='row', # ADD THIS!
    ))

if __name__ == '__main__':
    app.run_server(debug=True)
```

### error log

```
TypeError: _scale() takes 2 positional arguments but 3 were given

Traceback (most recent call last)
File "clustergram_check.py", line 58, in update_clustergram
standardize='row',
File "\Anaconda3\envs\my_project\lib\site-packages\dash_bio\component_factory\_clustergram.py", line 175, in Clustergram
**kwargs
File "\Anaconda3\envs\my_project\lib\site-packages\dash_bio\component_factory\_clustergram.py", line 343, in __init__
self._data = self._scale(self._data, standardize)
TypeError: _scale() takes 2 positional arguments but 3 were given
```

**Comment by mkcor** [comment]
@shammamah Our internal method `_scale()` takes two arguments: https://github.com/plotly/dash-bio/blob/6ca6b8a4f6d4cfe2846155a23f72c82b8162f229/dash_bio/component_factory/_clustergram.py#L715-L718
So this fix might not be sufficient, but it's at least necessary.

**Comment by shammamah** [comment]
@illumination-k Good catch :) Could you please add an entry in the CHANGELOG?

**Comment by mkcor** [comment]
@shammamah Do you mind if I sync up, merge, and submit a matching CHANGELOG entry right afterwards? This tiny PR has been open for too long...

**Comment by shammamah** [comment]
@mkcor Yes, please do! We can also probably release this as a patch version.

**Comment by mkcor** [comment]
@shammamah Ok, thanks! But we first need #443 to pass...

**Pull request merged**
