### PR TITLE
Update some JS dependencies and rebuild package.

### PR DESCRIPTION
**Pull request by mkcor**
## About
This is about managing JS dependencies.

## Description of changes
My original intention was to migrate to React 16 and Dash 0.42, but I'll tackle it next week. For now, I have only run:
```
npm install
npm audit fix
npm run build:all
```

I'm not sure what is going on with the following:
* is Renote Bot still running? (We haven't seen any of its automated PR in a while...)
* although we haven't migrated to React 16 as a dependency, we are using it as a dependency of dependency(??) https://github.com/plotly/dash-bio/blob/4c12d9206ba430c7c8ea431b116c9d035034b513/package-lock.json#L10775
* I have browsed the [docs](https://docs.npmjs.com/auditing-package-dependencies-for-security-vulnerabilities#security-vulnerabilities-found-requiring-manual-review) but haven't actually handled security vulnerabilities *manually* so far, and my understanding is that a `package-lock.json` file shouldn't be edited manually anyway... All this to say that I haven't addressed https://github.com/plotly/dash-bio/network/alert/dash_bio/package-lock.json/jquery/open in this PR.

fyi @Marc-Andre-Rivet 

## Before merging
- [ ] I have gone through the [code review checklist](https://github.com/plotly/dash-component-boilerplate/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/review_checklist.md)
- [ ] I have completed all of the [steps to take before merging](https://github.com/plotly/dash-bio/blob/master/.github/before_merging.md)
- [ ] I know how to [deploy to DDS](https://github.com/plotly/dash-bio/blob/master/.github/deploying_to_dds.md)

### CODE REVIEW

**Comment by mkcor** [comment]
@shammamah Please review.

What a pity! Our apps seem to work well on React 16 and Dash 0.42 (316a76b5b1) but, unfortunately, I can't run the test suite successfully... because `selenium` throws
```
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome version must be between 70 and 73
```
and it's not trivial to downgrade my Google Chrome 74.0.3729.131 to version 73. The issue is then reminiscent of https://github.com/SeleniumHQ/selenium/issues/6854.

I pushed 316a76b5b1 to see how CircleCI would handle this, but it's not enlightening. I meant to push it to another (not-yet-existing) remote branch, not to pollute this one, but that didn't work (pretty sure it used to work, creating the new remote branch on the fly?!).

**Comment by mkcor** [comment]
@Marc-Andre-Rivet I'm not sure what the *right* workflow is, in terms of upgrading JS packages, but I happily discovered the `npm outdated` command!

Then I ran `npm install <package-name>@latest` for each package I actually wanted to upgrade to its latest version, because it didn't feel right to edit `package.json` manually... When I was happy with the (shorter) output of `npm outdated`, I committed the (expected) changes to `package.json` and `package-lock.json`.

Do you commend my workflow? ;)

**Comment by shammamah** [comment]
@mkcor Can you please verify that OncoPrint still works as it should by locally running: 

```bash
pip uninstall -y dash-bio 
python setup.py install
```
and then running the onco print demo app?

**Comment by mkcor** [comment]
Sure. I'm running `python tests/dashbio_demos/app_onco_print.py` locally and exploring the apps, everything seems to be working fine... Why OncoPrint in particular? :)

**Comment by shammamah** [comment]
That seems to be the only package version that got updated, according to the diff in `package.json`. Thanks!

**Comment by mkcor** [comment]
Oh, sure! Wait, I'm still running React 16 and Dash 0.42 in my local environment!! Let me reinstall the previous environment.

**Comment by mkcor** [comment]
All good, I reinstalled my environment and checked that the OncoPrint app works. I didn't notice any difference.

Now, my whole `chromedriver`-Chrome setup is broken locally... Maybe we could switch to Firefox for `selenium` testing!!

**Comment by shammamah** [comment]
@mkcor Definitely something to look into! I'll approve in the meantime.

**Pull request merged**
