### PR TITLE
Handle some exceptions in demo apps.

### PR DESCRIPTION
**Pull request by mkcor**
Replaces #348.

## About
This is about [defensive programming](https://swcarpentry.github.io/python-novice-inflammation/reference/#defensive-programming).

## Description of changes
I can't think of a situation where `data` could be `None` once it's been decoded via `json.loads()`...

## Before merging
- [ ] I have gone through the [code review checklist](https://github.com/plotly/dash-component-boilerplate/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/review_checklist.md)
- [ ] I have completed all of the [steps to take before merging](https://github.com/plotly/dash-bio/blob/master/.github/before_merging.md)
- [ ] I know how to [deploy to DDS](https://github.com/plotly/dash-bio/blob/master/.github/deploying_to_dds.md)

### CODE REVIEW

**Comment by mkcor** [comment]
c1bf2b9 addresses https://github.com/plotly/dash-bio/pull/348#discussion_r284314503. For the sake of illustration,
```py
data = json.loads('[]')
```
works, but then
```py
data.keys()
```
leads to an `AttributeError` (related: https://stackoverflow.com/questions/18419428/what-is-the-minimum-valid-json).

**Comment by shammamah** [comment]
@mkcor - @mj3cheun has opened another PR (#353). We can close this one.

**Comment by shammamah** [comment]
Closing this as #353 has been merged in.

**Comment by mkcor** [comment]
@shammamah I realize that I didn't read

> @mkcor - @mj3cheun has opened another PR (#353). We can close this one.

carefully when you originally posted it (I misinterpreted it, like the other way around). I only submitted this PR because #353 seemed to be hanging and came from a fork (so I couldn't contribute to it directly). The intention is the same, of course, but I was trying to cover more cases where the code for loading data could break (example https://github.com/plotly/dash-bio/pull/352#issuecomment-492754672). Another example could be `data = {}`, in which case `data is None` would be `False`, so the next operation `data = json.loads(data)` would lead to a TypeError...

So I was hoping for @mj3cheun to either cherry-pick some of these commits (on this branch) or include the try/except code somehow (and possibly re-submit from a clone, as discussed privately).

**Pull request closed without merging**
